### ISSUE TITLE
Improve README/metadata?

### ISSUE THREAD

**Issue by CyrilBrulebois** [go-openapi/inflect#3]
Hi,

Still in the process of creating a Debian package, we're supposed to have a one-line short description, plus a longer one (that can span multiple paragraphs). Unfortunately, while I vaguely grasp what the libary does by looking at its code and function names, I wouldn't want to misrepresent what it's supposed to do exactly, or what it's capable of.

Could you please consider adding some description at the top of the README and in the repository's description? At the moment, all we kwow is that it's a fork from a project that went 404 (which broke the documented `go get` command, still pointing at BitBucket).

Thanks for considering!

Cheers,
Cyril.

**Comment by registergoofy** [comment]
Hi,

IMHO, I would go with something like this:

*short description*
golang library providing set of functions applying grammar rules to English words

*long description*
This golang library provides basic set of function applying grammar rules for inflecting English words and modify words case style (Capitalize, camelCase, snake_case...). Acronym are properly managed.

**Comment by CyrilBrulebois** [comment]
Thanks for the suggestion, I think I'll use the following (slightly adapted):

```
Description: golang library providing functions applying grammar rules to English words
 This golang library provides a basic set of functions applying
 grammar rules to inflect English words, and to modify case style
 (Capitalize, camelCase, snake_case, etc.). Acronyms are properly
 managed. A common use case is word pluralization.
```
